[package]
name = "fp-rpc"
version = "3.0.0-dev"
authors = ["Parity Technologies <admin@parity.io"]
edition = "2018"
description = "Runtime primitives for Ethereum RPC (web3) compatibility layer for Substrate."
license = "Apache-2.0"

[dependencies]
sp-core = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2021-11" }
sp-api = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2021-11" }
fp-evm = { version = "3.0.0-dev", default-features = false, path = "../../primitives/evm" }
ethereum = { git = "https://github.com/CocDap/ethereum", branch="5ire-11", default-features = false, features = ["with-codec"] }
ethereum-types = { version = "0.12", default-features = false }
codec = { package = "parity-scale-codec", version = "2.2.0", default-features = false }
sp-runtime = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2021-11" }
sp-std = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2021-11" }
sp-io = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2021-11" }
scale-info = { version = "1.0.0", default-features = false, features = ["derive"] }

[features]
default = ["std"]
std = [
	"sp-core/std",
	"sp-api/std",
	"fp-evm/std",
	"ethereum/std",
	"ethereum-types/std",
	"codec/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-io/std",
]
